### ISSUE TITLE
你好 出现问题

### ISSUE THREAD

**Issue by piokto** [pupilcc/pushbot#11]
白标错误页面
此应用程序没有配置的错误视图，因此您将其视为回退。

周六 10 月 29 日 21：24：49 CST 2022
[1eef6ab5] 出现意外错误（类型=未找到，状态=404）。

**Comment by pupilcc** [comment]
检查一下请求的地址对不对，404是地址不存在。

**Comment by pupilcc** [comment]
最好能贴一下输入的地址
