### ISSUE TITLE
消息格式化问题

### ISSUE THREAD

**Issue by ChenceGu** [pupilcc/pushbot#9]
POST给定parseMode时,返回failed
![image](https://user-images.githubusercontent.com/114282946/192455372-a7adcb88-480d-4b9f-89a0-b3115d489ac2.png)

**Comment by pupilcc** [comment]
![image](https://user-images.githubusercontent.com/47267788/192547796-57f3f0d5-bee0-45e4-92a5-8fb20365f192.png)
经测试，未能复现问题。

排查指引：
1. 确定推送消息时使用的 chatToken 是从 bot 生成的推送token，而不是 bot token。

如未能解决问题，希望能提供更多信息，包括不限于：是否是自建的，自建的版本是哪个。

**Comment by pupilcc** [comment]
![image](https://user-images.githubusercontent.com/47267788/192549123-e9d240a2-b472-4701-a0a4-bee4b73a0e81.png)
经测试，未能复现问题。

排查指引：
1. 确定推送消息时使用的链接和 chatToken 是从 bot 生成的
![image](https://user-images.githubusercontent.com/47267788/192550022-aa835d1e-f7d9-453b-b61b-35639b18a685.png)


如未能解决问题，希望能提供更多信息，包括不限于：是否是自建的，自建的版本是哪个。
